"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { useRouter } from "next/navigation";
import { useState, useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export function Navbar() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const router = useRouter();

  useEffect(() => {
    // Check if the user is logged in by verifying the token
    const token = localStorage.getItem("accessToken");
    if (token) {
      // You can also make an API request to verify the token if needed
      setIsLoggedIn(true);
    } else {
      setIsLoggedIn(false);
    }
  }, []);

  const handleLogout = () => {
    localStorage.removeItem("accessToken");
    setIsLoggedIn(false);
    router.push("/login"); // Redirect to login page
  };

  return (
    <div className="container mx-auto flex justify-between items-center">
      <a href="/" className="text-white text-2xl font-bold">
        Blog
      </a>
      <div>
        {isLoggedIn ? (
          <div className="flex space-x-4">
            <button
              className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-red-600"
              type="button"
            >
              <a href="/post/create" className="text-white">
                Create Post
              </a>
            </button>
            <button
              onClick={handleLogout}
              className="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600"
            >
              Logout
            </button>
          </div>
        ) : (
          <a
            href="/login"
            className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600"
          >
            Login
          </a>
        )}
      </div>
    </div>
  );
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Navbar />
        </nav>

        {children}
      </body>
    </html>
  );
}
