services:
  db:
    image: postgres:13
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: django_blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=django_blog
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    restart: on-failure
    volumes:
      - "./blog_project:/app/blog_project"
      
volumes:
  postgres_data:
